added command history
icedream/icecon pull request #10
Opened 2018-10-04 13:44 UTC by TheIndra55

This pull request adds a new feature which i really missed in the application, it allows you to press arrows up and down to easily get back the previously typed command

2018-10-04 18:59 UTC, icedream requested changes
Heyup,

just looked at the pull request and tested it on my computer. This is an awesome idea and it works really well so far!

A few things that I would like to mention.

First of all, make sure to format your code with [`gofmt`](https://golang.org/cmd/gofmt/); most editors have integration for it in some way and it helps making code styling for the whole source code repository consistent.

Secondly, I left a suggestion for limiting the history array to a size that is better to manage. What do you think about that?

Other than that, I'd be glad to merge this as part of the next release! Thanks for the code so far. :)

2018-10-04 18:59 UTC, icedream commented on main_windows.go
> +		historyIndex = len(history)
It might be a good idea to limit the history array to a small number like 20, 50 or maybe 100 to avoid having it grow unnecessarily.

2018-10-04 18:59 UTC, icedream commented on main_windows.go
> +
This whitespace error could probably be eliminated by `gofmt`.

2018-10-04 18:59 UTC, icedream commented on main_windows.go
> +			}else{
Running `gofmt` on this file will insert consistent spacing for cases like this.

2018-10-04 21:13 UTC, TheIndra55 commented
Hey

Thanks for your suggestions I formatted the code with `gofmt` and added a limit to the history array hope it's okay now 😄

2018-10-05 09:06 UTC, icedream approved these changes

2018-10-05 09:06 UTC, icedream commented
LGTM now :+1: 

Thanks for the contribution!

2018-10-05 09:07 UTC, merged